CREATE INDEX "idx_inventory_user_id" ON "inventory" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_card_id" ON "inventory" USING btree ("card_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_variant_id" ON "inventory" USING btree ("variant_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_player_id" ON "inventory" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_status" ON "inventory" USING btree ("listing_status");--> statement-breakpoint
CREATE INDEX "idx_inventory_grade_key" ON "inventory" USING btree ("grade_key");--> statement-breakpoint
CREATE INDEX "idx_offline_sync_user_id" ON "offline_sync_queue" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_trade_items_tx_id" ON "trade_items" USING btree ("transaction_id");--> statement-breakpoint
CREATE INDEX "idx_trade_items_inventory_id" ON "trade_items" USING btree ("inventory_id");--> statement-breakpoint
CREATE INDEX "idx_transactions_user_id" ON "transactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_transactions_inventory_id" ON "transactions" USING btree ("inventory_id");--> statement-breakpoint
CREATE INDEX "idx_transactions_customer_id" ON "transactions" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "idx_card_price_history_variant_id" ON "card_price_history" USING btree ("variant_id");--> statement-breakpoint
CREATE INDEX "idx_consumer_collection_user_id" ON "consumer_collection" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_consumer_collection_card_id" ON "consumer_collection" USING btree ("card_id");--> statement-breakpoint
CREATE INDEX "idx_image_hashes_card_id" ON "image_hashes" USING btree ("card_id");--> statement-breakpoint
CREATE INDEX "idx_image_hashes_variant_id" ON "image_hashes" USING btree ("variant_id");--> statement-breakpoint
CREATE INDEX "idx_platform_active_variant_id" ON "platform_active_listings" USING btree ("variant_id");--> statement-breakpoint
CREATE INDEX "idx_platform_sold_variant_id" ON "platform_sold_listings" USING btree ("variant_id");--> statement-breakpoint
CREATE INDEX "idx_price_alerts_user_id" ON "price_alerts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_price_alerts_card_id" ON "price_alerts" USING btree ("card_id");--> statement-breakpoint
CREATE INDEX "idx_want_list_user_id" ON "want_list" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_want_list_card_id" ON "want_list" USING btree ("card_id");