export const MOCK_TODAY_STATS = {
  date: '2026-04-15',
  cards_bought: 4,
  cards_sold: 3,
  total_spent: 640.00,
  total_revenue: 890.00,
  net_profit: 182.00,
  best_deal_margin: 65.7,
}

export const MOCK_TRANSACTIONS = [
  {
    id: 'tx-001',
    type: 'sell',
    player_name: 'CJ Stroud',
    set_name: 'Prizm Silver',
    grade_key: 'PSA_10',
    price: 198.00,
    cost_basis: 145.00,
    profit: 42.00,
    profit_pct: 28.9,
    platform_fee: 11.00,
    net_to_dealer: 187.00,
    channel: 'card_show',
    payment_method: 'cash',
    deal_rating: 'good_deal',
    created_at: '2026-04-15T09:15:00Z',
  },
  {
    id: 'tx-002',
    type: 'buy',
    player_name: 'Josh Allen',
    set_name: 'Prizm Silver',
    grade_key: 'PSA_10',
    price: 389.00,
    cost_basis: 389.00,
    profit: null,
    profit_pct: null,
    platform_fee: null,
    net_to_dealer: null,
    channel: 'card_show',
    payment_method: 'venmo',
    deal_rating: 'fair_price',
    created_at: '2026-04-15T10:30:00Z',
  },
  {
    id: 'tx-003',
    type: 'sell',
    player_name: 'Jayden Daniels',
    set_name: 'Prizm Silver',
    grade_key: 'RAW',
    price: 58.00,
    cost_basis: 35.00,
    profit: 23.00,
    profit_pct: 65.7,
    platform_fee: 0,
    net_to_dealer: 58.00,
    channel: 'card_show',
    payment_method: 'cashapp',
    deal_rating: 'good_deal',
    created_at: '2026-04-15T11:45:00Z',
  },
  {
    id: 'tx-004',
    type: 'buy',
    player_name: 'Luka Doncic',
    set_name: 'Prizm',
    grade_key: 'PSA_10',
    price: 210.00,
    cost_basis: 210.00,
    profit: null,
    profit_pct: null,
    platform_fee: null,
    net_to_dealer: null,
    channel: 'card_show',
    payment_method: 'zelle',
    deal_rating: 'good_deal',
    created_at: '2026-04-15T13:00:00Z',
  },
]

export const MOCK_CUSTOMERS = [
  {
    id: 'cust-001',
    name: 'John Martinez',
    email: 'john@gmail.com',
    phone: '+1-555-0101',
    total_transactions: 12,
    total_spent: 3240.00,
    last_seen_at: '2026-04-14T15:00:00Z',
    is_favorite: true,
    notes: 'Loves football rookies. Cash only.',
    initials: 'JM',
  },
  {
    id: 'cust-002',
    name: 'Sarah Lee',
    email: 'sarah@mail.com',
    phone: '+1-555-0102',
    total_transactions: 8,
    total_spent: 1890.00,
    last_seen_at: '2026-04-12T11:00:00Z',
    is_favorite: false,
    notes: 'Collects basketball vintage.',
    initials: 'SL',
  },
  {
    id: 'cust-003',
    name: 'Dave Wilson',
    email: 'dave.w@outlook.com',
    phone: '+1-555-0103',
    total_transactions: 22,
    total_spent: 8450.00,
    last_seen_at: '2026-04-15T09:30:00Z',
    is_favorite: true,
    notes: 'Best customer. High-end graded only.',
    initials: 'DW',
  },
]

export const MOCK_CARD_SEARCH_RESULTS = [
  { id: 'card-001', player_name: 'Patrick Mahomes', year: 2017, set_name: 'Prizm', variation: 'Silver', sport: 'Football' },
  { id: 'card-002', player_name: 'CJ Stroud',       year: 2023, set_name: 'Prizm', variation: 'Silver', sport: 'Football' },
  { id: 'card-003', player_name: 'Josh Allen',      year: 2018, set_name: 'Prizm', variation: 'Silver', sport: 'Football' },
  { id: 'card-004', player_name: 'Aaron Judge',     year: 2017, set_name: 'Topps Chrome', variation: 'Refractor', sport: 'Baseball' },
  { id: 'card-005', player_name: 'Jayden Daniels',  year: 2024, set_name: 'Prizm', variation: 'Silver', sport: 'Football' },
]
